### Create a New Event
POST http://localhost:3333/events
Content-Type: application/json

{
  "title": "INNX Grand Opening",
  "details": "Grand opening for INNX Business Club",
  "maximumAttendees": null,
  "price": null,
  "createdAt": "2024-04-08T14:55:32.302Z"
}

### Register a New Attendee
POST http://localhost:3333/events/396fffb3-c127-4f02-a3f2-e25decbdfd5e/attendees
Content-Type: application/json

{
  "name": "Diego Fernandes",
  "email": "diego@2rocketseat.com.br"
}

### Get Event Info
GET http://localhost:3333/events/4d581edb-3f8c-4224-9182-c4398cfea080

### Get Attendees Badge
GET http://localhost:3333/attendees/5lz2c7vfJa/badge

### Check In
GET http://localhost:3333/attendees/m8f6Nf5grD/check-in

### Get All Attendees
GET http://localhost:3333/events/4d581edb-3f8c-4224-9182-c4398cfea080/attendees

### Delete Attendee
DELETE http://localhost:3333/attendees/-70eviYCOI

### Edit Attendee Info
PUT http://localhost:3333/attendees/f9XG8ans5w
Content-Type: application/json

{
  "name": "Diego Fernandes",
  "isCheckedIn": true
}

### Get All Events
GET http://localhost:3333/events

### Delete Event
DELETE http://localhost:3333/events/2b4ea6ee-4345-4971-b475-bb7e21d824be