### Create a New Event
POST http://localhost:3333/events
Content-Type: application/json

{
  "title": "NLW SUMMIT",
  "maximumAttendees": 2
}

### Register a New Attendee
POST http://localhost:3333/events/2b4ea6ee-4345-4971-b475-bb7e21d824be/attendees
Content-Type: application/json

{
  "name": "Diego Fernandes",
  "email": "diego@rocketseat.com.br"
}

### Get Event Info
GET http://localhost:3333/events/2b4ea6ee-4345-4971-b475-bb7e21d824be

### Get Attendees Badge
GET http://localhost:3333/attendees/5lz2c7vfJa/badge

### Check In
GET http://localhost:3333/attendees/sEqFb9Yy1Z/check-in

### Get All Attendees
GET http://localhost:3333/events/2b4ea6ee-4345-4971-b475-bb7e21d824be/attendees

### Edit Attendee Info
PUT http://localhost:3333/attendees/sEqFb9Yy1Z/edit
Content-Type: application/json

{
  "name": "Diego Lopes",
  "checkedInAt": null
}