POST http://localhost:3333/events
Content-Type: application/json

{
  "title": "NLW Unite",
  "maximumAttendees": 1
}

###

POST http://localhost:3333/events/3c808fad-8868-4a2a-a441-c41d65071af0/attendees
Content-Type: application/json

{
  "name": "Diego Fernandes",
  "email": "diego3fernandes2@rocketseat.com.br"
}

###
GET http://localhost:3333/events/3c808fad-8868-4a2a-a441-c41d65071af0

###
GET http://localhost:3333/attendees/8DcM_TmsIe/badge